<a href="https://colab.research.google.com/github/yasvanthika122/Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
l1=[1,2,3]
print(l1)

[1, 2, 3]


In [2]:
l1=[1,2,3]
l2=[3,4,5]
l1.append(2)
print(l1)


[1, 2, 3, 2]


In [3]:
li = []
tup= (1, 2, 3)
li.append(tup)
print(li)


[(1, 2, 3)]


In [4]:
l1=[2,3,4]
l2=[7,8]
l1.append(l2)
print(l1)


[2, 3, 4, [7, 8]]


In [5]:
import numpy as np


In [6]:
arr = np.array([1, 2, 3, 4, 5])
shape=arr.shape
print(shape)

(5,)


In [7]:
print(type(arr))


<class 'numpy.ndarray'>


In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((4,3,2))

array([[[0.44585221, 0.72528866],
        [0.08338081, 0.69987627],
        [0.26633055, 0.20076319]],

       [[0.12271122, 0.22595564],
        [0.71647443, 0.1774901 ],
        [0.56079069, 0.83690873]],

       [[0.02166364, 0.82420176],
        [0.0632959 , 0.17777124],
        [0.72885239, 0.98438976]],

       [[0.62270947, 0.51902037],
        [0.16958784, 0.27286359],
        [0.3520446 , 0.67023262]]])

In [11]:
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [12]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
f=np.arange(10,50,5)
print(f)

[10 15 20 25 30 35 40 45]


In [14]:
np.arange(90,100,3)

array([90, 93, 96, 99])

In [15]:
np.linspace(0, 1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(9,15,num=12)

array([ 9.        ,  9.54545455, 10.09090909, 10.63636364, 11.18181818,
       11.72727273, 12.27272727, 12.81818182, 13.36363636, 13.90909091,
       14.45454545, 15.        ])

In [17]:
arr=(1,2,3,4,5)
print(arr)
print(arr[0])
print(arr[2:])

(1, 2, 3, 4, 5)
1
(3, 4, 5)


In [18]:
a=np.array([[1,2],[2,3],[6,7]])
print(a)
print(a[0,1])
print(a[1:3])

print(a[0:2,0])


[[1 2]
 [2 3]
 [6 7]]
2
[[2 3]
 [6 7]]
[1 2]


In [19]:
a=np.array([[3,4,5,1],[1,2,3,9],[9,4,3,1]])
print(a)
print()

r1=a[1,:]
print(r1)
print()

r2=a[0:2,:]
print(r2)
print()

r3=a[[1],:]
print(r3)

[[3 4 5 1]
 [1 2 3 9]
 [9 4 3 1]]

[1 2 3 9]

[[3 4 5 1]
 [1 2 3 9]]

[[1 2 3 9]]


In [20]:
a=np.array([[3,4,5,1],[1,2,3,9],[9,4,3,1]])
print(a)
print()

c1=a[:,1]
print(c1)
print()

c2=a[:,0:2]
print(c2)
print()

c3=a[:,[1]]
print(c3)

[[3 4 5 1]
 [1 2 3 9]
 [9 4 3 1]]

[4 2 4]

[[3 4]
 [1 2]
 [9 4]]

[[4]
 [2]
 [4]]
